name: app_motoservice
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.1
  flutter_dotenv: ^5.2.1
  google_fonts: ^6.2.1
  cloud_firestore: ^5.6.8
  form_builder_validators: ^11.1.2
  flutter_form_builder: ^10.0.1
  flutter_screenutil: ^5.9.3
  firebase_auth: ^5.5.4
  intl: ^0.19.0
  flutter_native_splash: ^2.4.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/.env
    - assets/img/

flutter_native_splash:
  android: true
  ios: true
  web: true

  image: "assets/img/logo.png"
  color: "#F9FAFB"

  android_12:
    color: "#F9FAFB"
    image: "assets/img/logo.png"